const socket = io();
let state = null, current = 'photo', selectedOrder = [], archiveOrder = [], cipherShift = 0, photoClues = new Set(), socialChecks = new Set();
let avatar = 'Nora';
const $ = (s) => document.querySelector(s);
const rooms = [
  ['photo', '01', 'La fotografía'], ['social', '02', 'La red social'], ['archive', '03', 'Archivo roto'], ['decoder', '04', 'Mesa de cifrado'],
  ['puzzle', '05', 'El rompecabezas'], ['detective', '06', 'El detective'], ['classify', '07', 'Verdad o engaño'], ['final', '∞', 'La edición']
];
const messages = [
  '“No desperdicien ni un clic.”', '“Ese titular tiene potencial. ¿Seguro que quieren comprobar la fuente?”',
  '“El contexto puede esperar. La tendencia no.”', '“Tres millones de personas esperan una historia. Publiquen ya.”', '“Una cifra sin contexto siempre parece más grande.”'
];

function toast(text) { const el = $('#toast'); el.textContent = text; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 3500); }
function name() { return `${$('#player-name').value.trim() || 'Periodista'} · ${avatar}`; }
document.querySelectorAll('.avatar').forEach(btn => btn.onclick = () => { avatar = btn.dataset.avatar; document.querySelectorAll('.avatar').forEach(x => x.classList.toggle('active', x === btn)); });
function showOnly(view) { ['landing','lobby','game'].forEach(id => { $(`#${id}`).hidden = id !== view; }); }
function enterRoom(next) { state = next; showOnly('lobby'); drawLobby(); }

$('#create-room').onclick = () => socket.emit('room:create', { name: name() }, (r) => r.ok && enterRoom(r.state));
$('#join-room').onclick = () => {
  const code = $('#join-code').value.trim().toUpperCase();
  if (code.length !== 4) return $('#landing-error').textContent = 'Escribe el código de cuatro caracteres.';
  socket.emit('room:join', { code, name: name() }, (r) => r.ok ? enterRoom(r.state) : $('#landing-error').textContent = r.error);
};
$('#join-code').addEventListener('keydown', (e) => { if (e.key === 'Enter') $('#join-room').click(); });
$('#copy-code').onclick = async () => { await navigator.clipboard.writeText(state.code); toast('Código copiado'); };
$('#start-game').onclick = () => socket.emit('game:start', { code: state.code });

socket.on('room:update', (next) => { state = next; if (state.started) showGame(); else drawLobby(); drawGame(); });

function drawLobby() {
  $('#room-code').innerHTML = [...state.code].map(letter => `<i style="display:grid;place-items:center;width:52px;height:61px;border:1px solid #31566b;border-radius:8px;background:#101a2b;font:700 28px Space Mono;font-style:normal">${letter}</i>`).join(''); $('#player-count').textContent = state.players.length;
  $('#player-list').innerHTML = state.players.map(p => `<span class="player">${escapeHtml(p.name)}${p.id === state.hostId ? ' · anfitrión' : ''}</span>`).join('');
  const host = socket.id === state.hostId; $('#start-game').hidden = !host; $('#host-note').hidden = host;
}
function showGame() { showOnly('game'); }
function escapeHtml(t) { const d = document.createElement('div'); d.textContent = t; return d.innerHTML; }
function solved(id) { return state.solved.includes(id); }
function isUnlocked(id, i) {
  if (id === 'classify') return state.solved.length >= 6;
  if (id === 'final') return state.solved.length >= 6 && state.classifications.done;
  return i === 0 || solved(rooms[i - 1][0]);
}
function drawGame() {
  if (!state?.started) return;
  $('#progress').textContent = `${state.solved.length + (state.classifications.done ? 1 : 0)} / 7`;
  $('#room-nav').innerHTML = rooms.map(([id, no, title], i) => `<button class="${current === id ? 'active ' : ''}${!isUnlocked(id, i) ? 'locked' : ''}" data-room="${id}">${solved(id) || (id === 'classify' && state.classifications.done) ? '✓' : no} · ${title}</button>`).join('');
  $('#room-nav').querySelectorAll('button').forEach(b => b.onclick = () => { const i = rooms.findIndex(r => r[0] === b.dataset.room); if (!isUnlocked(b.dataset.room, i)) return toast('Primero recuperen el archivo anterior.'); current = b.dataset.room; drawGame(); });
  $('#evidence-list').innerHTML = state.evidence.map(e => `<span class="tag">${e}</span>`).join('') || '<span class="tag">Sin pruebas</span>';
  if (state.finalWon) return sceneWin();
  renderScene();
}
function header(no, title, intro) { return `<div class="scene-header"><small>ARCHIVO ${no}</small><h2>${title}</h2></div>${intro ? `<p class="brief">${intro}</p>` : ''}`; }
function submitPuzzle(id, answer) { socket.emit('game:solve', { code: state.code, puzzle: id, answer }, (r) => { toast(r.message); if (r.ok) setTimeout(() => { const ix = rooms.findIndex(x => x[0] === id); current = rooms[ix + 1][0]; drawGame(); }, 600); }); }
function inputPuzzle(id, placeholder) { return `<div class="answer-row"><input id="answer" placeholder="${placeholder}" autocomplete="off"><button id="submit">Validar</button></div>`; }
function renderScene() {
  const scene = $('#scene');
  if (solved(current)) { scene.innerHTML = header('RECUPERADO', rooms.find(r => r[0] === current)?.[2] || '') + `<div class="paper"><h3>Archivo seguro</h3><p>Esta evidencia ya está en el expediente. Continúen con la siguiente sala.</p></div>`; return; }
  if (current === 'photo') scene.innerHTML = header('01', 'Verificación visual', 'El pie de foto fue alterado. Contrasta el registro de emergencia, la meteorología y los metadatos antes de decidir qué imagen puede ilustrar el caso.') + `<article class="paper"><div class="source-line"><b>REGISTRO 24-07</b>: evacuación, Barrio Central, 18:40. &nbsp; <b>METEO</b>: lluvia intensa desde 18:10. &nbsp; <b>PIE VIRAL</b>: “inundación en Puerto Norte”.</div><div class="photo-grid"><div class="photo choice-photo" data-photo="wrong"><b>Imagen A · lluvia ligera</b><span class="hotspot" data-clue="a-date" style="top:42%;left:47%">17 JUL 2017</span><span class="hotspot" data-clue="a-place" style="top:18%;right:12%">PUERTO NORTE</span></div><div class="photo two choice-photo" data-photo="right"><b>Imagen B · lluvia intensa</b><span class="hotspot" data-clue="b-date" style="top:40%;left:45%">24 JUL 2024</span><span class="hotspot" data-clue="b-place" style="bottom:29%;right:14%">BARRIO CENTRAL</span></div></div><div class="clue" id="photo-clue">No busques una coincidencia aislada: solo una imagen satisface fecha, lugar y condiciones. Metadatos: 0 / 3.</div></article>`;
  if (current === 'social') scene.innerHTML = header('02', 'Cadena de fuentes', 'Ningún número de reacciones es evidencia. Audita las tres publicaciones y decide cuál permite reconstruir autor, fecha, datos y método.') + `<article class="paper"><div class="source-line"><b>CRITERIO DE ADMISIÓN</b>: una fuente entra al expediente solo si identifica quién produjo los datos, cuándo, con qué muestra y dónde consultar el documento íntegro.</div><div class="post play-post" data-post="viral"><b>@alerta_ahora</b><p>“El 82 % ya lo sabe. Compártelo antes de que lo oculten.”</p><small>12.4 mil compartidos · enlace redirige a una página sin autor · cifra sin documento</small></div><div class="post play-post" data-post="capture"><b>@datos_sin_filtro</b><p>“Esta captura demuestra que los medios nos mienten.”</p><small>8.1 mil compartidos · fecha cortada · usuario sin identificación · sin metodología</small></div><div class="post verified play-post" data-post="source"><b>@observatorio_publico</b><p>“Los datos muestran una variación mensual; el informe completo explica sus límites.”</p><small>Autor institucional · 08:14 · enlace al conjunto de datos, muestra y metodología</small></div><div class="clue" id="social-clue">Audita cada ficha. No se habilita una decisión hasta completar el rastreo de las tres.</div></article>`;
  if (current === 'archive') scene.innerHTML = header('03', 'Archivo roto', 'Reconstruye la cadena de publicación. Selecciona las tarjetas una por una en el orden real. Un clic equivocado reinicia el intento.') + `<div class="click-game"><button class="play-card archive-card" data-archive="1"><b>01</b><br><small>09:47 · Una cuenta viral copia el titular alterado.</small></button><button class="play-card archive-card" data-archive="2"><b>02</b><br><small>10:21 · El algoritmo recomienda el contenido.</small></button><button class="play-card archive-card" data-archive="3"><b>03</b><br><small>08:14 · La fuente primaria publica el informe.</small></button><button class="play-card archive-card" data-archive="4"><b>04</b><br><small>08:32 · Medio A resume los datos.</small></button></div><div class="clue" id="archive-clue">Cadena reconstruida: vacía.</div>`;
  if (current === 'decoder') scene.innerHTML = header('04', 'Mesa de cifrado', 'Activa el decodificador. El Editor desplazó cada letra una posición hacia adelante; ajusta la rueda hasta leer una palabra útil.') + `<div class="paper"><small class="eyebrow">SEÑAL INTERCEPTADA</small><div id="cipher-output" class="headline">WFSJGJDB</div><div class="answer-row"><button id="shift-back">−</button><div style="padding:12px;color:var(--muted);font-family:Space Mono">DESPLAZAMIENTO <b id="shift-value">0</b></div><button id="shift-forward">+</button></div><div class="clue">Cuando la señal tenga sentido, abre el expediente. La palabra final es una acción, no un nombre.</div><button id="decode-submit" class="primary">Abrir expediente</button></div>`;
  if (current === 'puzzle') scene.innerHTML = header('05', 'Arquitectura de la noticia', 'Ordena la estructura sin la cual un lector no puede distinguir un dato, su procedencia y la interpretación del medio.') + `<div class="paper"><div class="source-line"><b>REGLA DE LA MESA</b>: un titular puede atraer, pero no debe reemplazar el hecho ni esconder la fuente. La explicación depende del contexto; el contexto no puede ir antes de saber qué ocurrió.</div><div id="order" class="order-slots"></div><div class="clue">Selecciona la secuencia de publicación. Si alteras el orden, la conclusión puede parecer un hecho y la fuente queda invisible.</div><button id="check-order" class="primary">Cerrar estructura</button></div>`;
  if (current === 'detective') scene.innerHTML = header('06', 'El detective digital', 'Usa la línea temporal para aislar el primer cambio de significado. Solo puedes acusar cuando hayas inspeccionado los cuatro registros.') + `<div class="paper"><div class="timeline"><div class="trace" data-trace="source"><b>08:14</b> Fuente original publica el informe.</div><div class="trace" data-trace="a"><b>08:32</b> Medio A resume los datos sin cambiar el sentido.</div><div class="trace" data-trace="b"><b>09:05</b> Medio B añade “confirman” a su titular.</div><div class="trace" data-trace="viral"><b>09:47</b> La publicación viral copia el titular de Medio B.</div></div><div class="clue" id="trace-clue">Registros inspeccionados: 0 / 4.</div><div class="final-options"><button class="choice" data-accuse="MEDIO A">Acusar a Medio A</button><button class="choice" data-accuse="MEDIO B">Acusar a Medio B</button></div></div>`;
  if (current === 'classify') scene.innerHTML = header('07', '¿Verdad o engaño?', 'Clasifica cada frase según lo que realmente permite afirmar la evidencia.') + `<div class="classify"><div class="statement"><p>“El 70 % de estudiantes encuestados prefirió la opción A.”</p>${select('s1')}</div><div class="statement"><p>“Los estudiantes claramente odian la opción B.”</p>${select('s2')}</div><div class="statement"><p>“La preferencia por A podría explicar parte del resultado.”</p>${select('s3')}</div></div><button id="check-classify" class="primary">Recuperar clave</button>`;
  if (current === 'final') scene.innerHTML = header('FINAL', 'La edición', 'Han recuperado el expediente. Ahora decidan qué titular respeta la información disponible.') + `<div class="paper"><small class="eyebrow">INFORME ORIGINAL</small><h3>Expertos analizan los datos preliminares de una investigación en curso</h3><p>El estudio no permite todavía confirmar causas ni anticipar resultados definitivos.</p></div><div class="final-options" style="margin-top:18px"><button class="choice" data-choice="A">A. ¡ESCÁNDALO TOTAL! Los datos lo prueban todo</button><button class="choice" data-choice="B">B. Expertos analizan datos preliminares de una investigación en curso</button><button class="choice" data-choice="C">C. Nadie quiere que sepas lo que ocurre</button><button class="choice" data-choice="D">D. Esto demuestra una verdad oculta</button></div>`;
  bindScene();
}
function select(id) { return `<select id="${id}"><option value="">Clasificar…</option><option value="hecho">Hecho</option><option value="interpretacion">Interpretación</option><option value="manipulacion">Manipulación</option></select>`; }
function bindScene() {
  document.querySelectorAll('[data-clue]').forEach(el => el.onclick = (e) => { e.stopPropagation(); photoClues.add(el.dataset.clue); el.style.background = '#edbd48'; $('#photo-clue').textContent = `Caso: evacuación preventiva en Barrio Central, 24 de julio de 2024. Metadatos encontrados: ${photoClues.size} / 3.`; });
  document.querySelectorAll('[data-photo]').forEach(el => el.onclick = () => { if (photoClues.size < 3) return toast('Aún faltan metadatos. Examinen ambas imágenes.'); if (el.dataset.photo === 'right') { el.classList.add('selected'); submitPuzzle('photo', '2417'); } else toast('Esa imagen pertenece a otro año y a otro lugar.'); });
  document.querySelectorAll('[data-post]').forEach(el => el.onclick = () => { const type = el.dataset.post; socialChecks.add(type); el.classList.add('selected'); const notes = {viral:'El enlace termina en una página sin autor ni documento.',capture:'La captura no permite comprobar fecha, autor ni origen.',source:'El enlace lleva a la metodología y al informe original.'}; $('#social-clue').textContent = `${notes[type]} Fichas auditadas: ${socialChecks.size} / 3.`; if (socialChecks.size === 3 && socialChecks.has('source')) submitPuzzle('social', 'FUENTE'); });
  document.querySelectorAll('.archive-card').forEach(el => el.onclick = () => { const n = el.dataset.archive; if (archiveOrder.includes(n)) return; archiveOrder.push(n); el.classList.add('selected'); $('#archive-clue').textContent = `Cadena reconstruida: ${archiveOrder.join(' → ')}.`; if (archiveOrder.length === 4) { if (archiveOrder.join(',') === '3,4,1,2') submitPuzzle('archive','3,1,4,2'); else { toast('La cadena no coincide. Las tarjetas se reiniciaron.'); archiveOrder=[]; document.querySelectorAll('.archive-card').forEach(c=>c.classList.remove('selected')); $('#archive-clue').textContent='Cadena reconstruida: vacía.'; } } });
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'; const decode = () => { const value = 'WFSJGJDB'.split('').map(ch => alphabet[(alphabet.indexOf(ch) + cipherShift + 26) % 26]).join(''); $('#cipher-output').textContent = value; $('#shift-value').textContent = cipherShift; return value; }; if ($('#shift-back')) { $('#shift-back').onclick=()=>{cipherShift--;decode()};$('#shift-forward').onclick=()=>{cipherShift++;decode()};$('#decode-submit').onclick=()=>{if(decode()==='VERIFICA')submitPuzzle('decoder','VERIFICA');else toast('Todavía es ruido. Ajusten la rueda.')}};
  const seenTrace=new Set();document.querySelectorAll('.trace').forEach(el=>el.onclick=()=>{seenTrace.add(el.dataset.trace);el.style.color='#4de6d1';$('#trace-clue').textContent=`Registros inspeccionados: ${seenTrace.size} / 4.`});document.querySelectorAll('[data-accuse]').forEach(el=>el.onclick=()=>{if(seenTrace.size<4)return toast('Inspeccionen todos los registros antes de acusar.');submitPuzzle('detective',el.dataset.accuse)});
  const input = $('#answer'), submit = $('#submit'); if (submit) { submit.onclick = () => submitPuzzle(current, input.value); input.onkeydown = e => { if (e.key === 'Enter') submit.click(); }; }
  if (current === 'puzzle') { const cards = [['TITULAR','Titular'],['HECHO','Hecho'],['FUENTE','Fuente'],['CONTEXTO','Contexto'],['EXPLICACION','Explicación']]; const holder = $('#order'); const render = () => holder.innerHTML = cards.map(([v,t]) => `<button class="${selectedOrder.includes(v)?'selected':''}" data-v="${v}">${selectedOrder.indexOf(v) >= 0 ? selectedOrder.indexOf(v)+1+'. ' : ''}${t}</button>`).join(''); render(); holder.onclick = e => { const v=e.target.dataset.v;if(!v)return; selectedOrder.includes(v)?selectedOrder=selectedOrder.filter(x=>x!==v):selectedOrder.push(v);render();}; $('#check-order').onclick=()=>submitPuzzle('puzzle',selectedOrder.join(',')); }
  if (current === 'classify') $('#check-classify').onclick = () => socket.emit('game:classify', { code: state.code, values: [$('#s1').value,$('#s2').value,$('#s3').value] }, r => { toast(r.message); if(r.ok){current='final';drawGame();} });
  document.querySelectorAll('.choice').forEach(b => b.onclick = () => socket.emit('game:final', { code: state.code, choice: b.dataset.choice }, r => toast(r.message || (r.ok ? 'Edición reconstruida.' : ''))));
}
function sceneWin() { $('#scene').innerHTML = `<section class="win"><small class="eyebrow">SISTEMA DESBLOQUEADO</small><h2>La edición fue recuperada.</h2><p>La noticia nunca fue completamente falsa. El problema era todo aquello que faltaba.</p><strong>¿Cuántos clics vale la verdad?</strong><p style="font:13px 'DM Mono';margin-top:35px">EQUIPO: ${state.players.length} PERIODISTAS · EVIDENCIAS: ${state.evidence.length}</p></section>`; }
setInterval(() => { if (state?.started && !state.finalWon) $('#editor-text').textContent = messages[Math.floor(Math.random()*messages.length)]; }, 16000);
